### ISSUE TITLE
你好，想问下，关于require('module')

### ISSUE THREAD

**Issue by stone-jin** [midwayjs/module-hook#6]
这个里面我看到你使用shimmer，wrap了_compile和_findPath这两个函数，为什么能想到_compile和_findPath呢？这个资料是看的哪个？模块加载机制？

**Comment by mariodu** [comment]
参见 node.js 源码：https://github.com/nodejs/node/blob/25840529e31bfbdd6de6f527f1651e3e2cd22e69/lib/internal/modules/cjs/loader.js

**Comment by stone-jin** [comment]
强，你们都看过node.js的源码...向大佬学习
